project:
  type: website

website:
  title: "Ryo's Tech Blog: R 備忘録編"
  navbar:
    right:
      - about.qmd
      - text: Ryo's Tech Blog
        href: https://ryonakagami.github.io/
      - icon: github
        href: https://github.com/RyoNakagami
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
